version: '3.8'

services:
  backend:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:16.3-bookworm
    volumes:
      - uptime-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  uptime-pg-data: